// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcib0RtX6RWrW5y9MYkUvh_a-aq1pqvxY',
    appId: '1:961058682017:web:79ed19d3529a08f7fc6ce0',
    messagingSenderId: '961058682017',
    projectId: 'letsmeet-cspj',
    authDomain: 'letsmeet-cspj.firebaseapp.com',
    storageBucket: 'letsmeet-cspj.appspot.com',
    measurementId: 'G-PHTHLL9NTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHmmxkkDheRhiu2yrmLhhV7NmIoAGhvOE',
    appId: '1:961058682017:android:ef6a511c94b79e68fc6ce0',
    messagingSenderId: '961058682017',
    projectId: 'letsmeet-cspj',
    storageBucket: 'letsmeet-cspj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRHk3GjEctT3mt31TIU_dS_UA8VKNEbMA',
    appId: '1:961058682017:ios:4382747b74301cadfc6ce0',
    messagingSenderId: '961058682017',
    projectId: 'letsmeet-cspj',
    storageBucket: 'letsmeet-cspj.appspot.com',
    iosClientId: '961058682017-c6gekgvshm1mf7tkikrna9n7fjhv7uo3.apps.googleusercontent.com',
    iosBundleId: 'com.letsmeet.letsmeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRHk3GjEctT3mt31TIU_dS_UA8VKNEbMA',
    appId: '1:961058682017:ios:4382747b74301cadfc6ce0',
    messagingSenderId: '961058682017',
    projectId: 'letsmeet-cspj',
    storageBucket: 'letsmeet-cspj.appspot.com',
    iosClientId: '961058682017-c6gekgvshm1mf7tkikrna9n7fjhv7uo3.apps.googleusercontent.com',
    iosBundleId: 'com.letsmeet.letsmeet',
  );
}
